// 移动端菜单
const navToggle=document.getElementById('navToggle'),menu=document.getElementById('menu');
if(navToggle)navToggle.addEventListener('click',()=>menu.classList.toggle('open'));
if(menu)menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));

// 滚动渐显
const io=new IntersectionObserver(es=>es.forEach(e=>{
  if(!e.isIntersecting)return;
  const sib=e.target.parentElement?e.target.parentElement.children:[];
  const idx=Array.from(sib).indexOf(e.target);
  e.target.style.transitionDelay=Math.min(idx*70,350)+'ms';
  e.target.classList.add('in');io.unobserve(e.target);
}),{threshold:.15});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));

// 公司图片：色块 → 图片滚动浮现
const fio=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');fio.unobserve(e.target)}}),{threshold:.35});
document.querySelectorAll('.about-visual .frame').forEach(f=>fio.observe(f));

// 数字滚动
const cio=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,n=+el.dataset.count,d=1400,t0=performance.now();(function tick(t){const p=Math.min((t-t0)/d,1);el.textContent=Math.round(n*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)})(t0);cio.unobserve(el)}),{threshold:.6});
document.querySelectorAll('[data-count]').forEach(el=>cio.observe(el));

// 选项卡（产品筛选/IR 分类）
document.querySelectorAll('.tabs').forEach(group=>{
  group.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{
    group.querySelectorAll('.tab').forEach(t=>t.classList.remove('on'));
    tab.classList.add('on');
  }));
});

// 演示表单
document.querySelectorAll('form[data-demo]').forEach(f=>f.addEventListener('submit',e=>{
  e.preventDefault();
  const btn=f.querySelector('[type=submit]');
  if(btn){btn.textContent='已提交（演示）';btn.disabled=true;}
}));

// 应用领域卡片：点击展开详情（不跳转）
document.querySelectorAll('.app-card').forEach(card=>{
  card.addEventListener('click',()=>card.classList.toggle('open'));
});

// 产品中心：分类筛选
document.querySelectorAll('.filter-bar .fbtn').forEach(btn=>{
  btn.addEventListener('click',()=>{
    document.querySelectorAll('.filter-bar .fbtn').forEach(b=>b.classList.remove('on'));
    btn.classList.add('on');
    const f=btn.dataset.filter;
    document.querySelectorAll('.pcard').forEach(card=>{
      const show=f==='all'||card.dataset.cat===f;
      if(show){card.style.display='';requestAnimationFrame(()=>card.classList.remove('hide'));}
      else{card.classList.add('hide');setTimeout(()=>{if(card.classList.contains('hide'))card.style.display='none';},280);}
    });
  });
});

// 产品详情页：从 URL hash 读取产品名，并填充产品专属内容
const PRODUCTS={
  'PA6 无填充系列':{"sub":"PA6 无填充系列 · N6100 · 一般注塑级","meta":{"desc":"一般注塑级","model":"N6100","feature":"通用级","apps":"电子电器，电子接插件，一般工业结构件，尼龙扎带，卡扣，玩具"},"intro":"Kitech高性能尼龙6.66复合材料系列： 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["通用级"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["一般注塑级","N6100","通用级","电子电器，电子接插件，一般工业结构件，尼龙扎带，卡扣，玩具"],["脱模改善级","N6100H","高流动，脱模改善，自润滑","电子电器，线圈骨架，电器外壳"],["耐候级","N6100-UV","耐候，耐黄变","电器外壳，户外产品"]],"apps":[["⚡","电子电器"],["⚡","电子接插件"],["🔧","一般工业结构件"],["🔗","尼龙扎带"],["🔗","卡扣"],["🧸","玩具"]],"img":"images/product-pa.jpg"},
  'PA6 玻纤增强系列':{"sub":"PA6 玻纤增强系列 · N6110G · PA6+10%GF","meta":{"desc":"PA6+10%GF","model":"N6110G","feature":"10%GF增强，优异机械性能","apps":"汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"},"intro":"Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["10%GF增强","优异机械性能"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA6+10%GF","N6110G","10%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA6+15%GF","N6115G","15%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA6+30%GF","N6130G","30%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA6+50%GF","N6150G","50%GF增强，超高弯曲模量","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA6+60%GF","N6160G","60%GF增强，超高弯曲模量","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"]],"apps":[["🚗","汽车零部件"],["🏋","运动器材"],["👶","婴儿童车结构件"],["🏋","电动工具"],["🔧","办公家具"],["📺","小家电外壳"]],"img":"images/product-pa.jpg"},
  'PA6 增韧耐寒系列':{"sub":"PA6 增韧耐寒系列 · N6110R · PA6+5%增韧剂","meta":{"desc":"PA6+5%增韧剂","model":"N6110R","feature":"5%增韧剂，低温耐寒","apps":"汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"},"intro":"Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["5%增韧剂","低温耐寒"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA6+5%增韧剂","N6110R","5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA6+10%增韧剂","N6120R","10%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA6+15%GF+5%增韧剂","N6115SG","15%GF增强，5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA6+30%GF+5%增韧剂","N6130SG","30%GF增强，5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"]],"apps":[["🚗","汽车零部件"],["🏋","运动器材"],["👶","婴儿童车结构件"],["🏋","电动工具"],["🔗","脚轮"],["🔗","扎带"]],"img":"images/product-pa.jpg"},
  'PA6 矿纤增强系列':{"sub":"PA6 矿纤增强系列 · N6110M · PA6+10%MF","meta":{"desc":"PA6+10%MF","model":"N6110M","feature":"10%矿物填充，表面优异，抗变形","apps":"汽车零部件，工业风扇，电器结构件，汽车发动机盖罩，电器底座，隔热条，轮毂盖"},"intro":"Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["10%矿物填充","表面优异","抗变形"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA6+10%MF","N6110M","10%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩，电器底座，隔热条，轮毂盖"],["PA6+15%MF","N6115M","15%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩，电器底座，隔热条，轮毂盖"],["PA6+30%MF","N6130M","30%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩，电器底座，隔热条，轮毂盖"],["PA6+20%MF+10%GF","N6120M2G","20%矿物填充，10%玻纤增强，尺寸安定","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩"],["PA6+25%MF+15%GF","N6125M3G","25%矿物填充，15%玻纤增强，尺寸安定","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩"]],"apps":[["🚗","汽车零部件"],["🔧","工业风扇"],["⚡","电器结构件"],["🚗","汽车发动机盖罩"],["⚡","电器底座"],["🔧","隔热条"]],"img":"images/product-pa.jpg"},
  'PA6 碳纤增强系列':{"sub":"PA6 碳纤增强系列 · N6115T · PA6+15%TF","meta":{"desc":"PA6+15%TF","model":"N6115T","feature":"10%碳纤增强，超高弯曲强度","apps":"车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"},"intro":"Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["10%碳纤增强","超高弯曲强度"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA6+15%TF","N6115T","10%碳纤增强，超高弯曲强度","车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"],["PA6+30%TF","N6130T","30%碳纤增强，超高弯曲强度","车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"],["PA6+45%TF","N6145T","45%碳纤增强，超高弯曲强度","车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"],["PA6+15%TF+15%GF","N6115T3G","15%碳纤增强，15%玻纤增强","车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"]],"apps":[["👶","车零部件"],["🏋","运动器材"],["🔧","工业产品结构件"],["🔧","无人机浆叶"],["🔧","导电结构件"]],"img":"images/product-pa.jpg"},
  'PA6 阻燃系列':{"sub":"PA6 阻燃系列 · NFB6100 · PA6 V0阻燃级","meta":{"desc":"PA6 V0阻燃级","model":"NFB6100","feature":"表面优异，流动性好","apps":"电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"},"intro":"高性能尼龙复合材料 图片点进来左边是对应的配图， 右边是如下特性介绍： Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["表面优异","流动性好"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA6 V0阻燃级","NFB6100","表面优异，流动性好","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA6+10-30%GF+V0 溴锑阻燃级","NFB6110G，NFB6130G","高强度阻燃材料，流动性佳，易脱模，适合薄壁产品","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA6+10-30%GF+V0 红磷阻燃级","NFB6110G-P，NFB6130G-P","不含卤素与锑，低烟密度，CTI＞350V","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA6+10-30%GF+V0 无卤阻燃级","NFB6110G-HF，NFB6130G-HF","不含卤素与锑，低比重，高强度，高白度，着色效果好，高CTI值＞500V，耐高压","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA6+30%MF+V0阻燃级","NFB6130M","30%矿物增强，V0阻燃级","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"]],"apps":[["⚡","电子电器"],["⚡","家用电器"],["⚡","线圈骨架"],["🚗","汽车零部件"],["🚗","汽车散热风扇"],["⚡","连接器"]],"img":"images/product-pa.jpg"},
  'PA6 其他系列':{"sub":"PA6 其他系列 · N6130G-HS · PA6+30%GF 热稳定级","meta":{"desc":"PA6+30%GF 热稳定级","model":"N6130G-HS","feature":"30%GF增强，热稳定性优","apps":"汽车发动机周边，散热风扇，电子电器"},"intro":"高性能尼龙复合材料 图片点进来左边是对应的配图， 右边是如下特性介绍： Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["30%GF增强","热稳定性优"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA6+30%GF 热稳定级","N6130G-HS","30%GF增强，热稳定性优","汽车发动机周边，散热风扇，电子电器"],["PA6+30%GF 耐水解级","N6130G-WS","30%GF增强，耐水解性优","汽车水箱配件，水泵配件，水浴配件"],["PA6+30%GF 高模量级","N6130GBKV","30%GF增强，超高抗冲击模量","婴儿童车结构件，运动器材结构件"],["PA6+30%GF 热稳定级","N6130G-HS","30%GF增强，热稳定性优","汽车发动机周边，散热风扇，电子电器"]],"apps":[["🚗","汽车发动机周边"],["🚗","散热风扇"],["⚡","电子电器"]],"img":"images/product-pa.jpg"},
  'PA66 无填充系列':{"sub":"PA66 无填充系列 · N6200 · 一般注塑级","meta":{"desc":"一般注塑级","model":"N6200","feature":"一般通用级","apps":"电子电器，电子接插件，一般工业结构件，卡扣，玩具"},"intro":"Kitech高性能尼龙6.66复合材料系列： 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["一般通用级"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["一般注塑级","N6200","通用级","电子电器，电子接插件，一般工业结构件，卡扣，玩具"],["脱模改善级","N6200H","高流动，脱模改善，自润滑","电子电器，线圈骨架，电器外壳，汽车扎带"],["耐候级","N6200-UV","耐候，耐黄变","电子电器，户外用品"]],"apps":[["⚡","电子电器"],["⚡","电子接插件"],["🔧","一般工业结构件"],["🔗","卡扣"],["🧸","玩具"]],"img":"images/product-pa.jpg"},
  'PA66 玻纤增强系列':{"sub":"PA66 玻纤增强系列 · N6210G · PA66+10%GF","meta":{"desc":"PA66+10%GF","model":"N6210G","feature":"10%GF增强，优异机械性能","apps":"汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"},"intro":"Kitech高性能尼龙6.66复合材料系列： 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["10%GF增强","优异机械性能"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA66+10%GF","N6210G","10%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA66+15%GF","N6215G","15%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA66+30%GF","N6230G","30%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA66+50%GF","N6250G","50%GF增强，超高弯曲模量","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"]],"apps":[["🚗","汽车零部件"],["🏋","运动器材"],["👶","婴儿童车结构件"],["🏋","电动工具"],["🔧","办公家具"],["📺","小家电外壳"]],"img":"images/product-pa.jpg"},
  'PA66 增韧耐寒系列':{"sub":"PA66 增韧耐寒系列 · N6210R · PA66+5%增韧剂","meta":{"desc":"PA66+5%增韧剂","model":"N6210R","feature":"5%增韧剂，低温耐寒","apps":"汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"},"intro":"Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["5%增韧剂","低温耐寒"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA66+5%增韧剂","N6210R","5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA66+10%增韧剂","N6220R","10%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA66+15%GF+5%增韧剂","N6215SG","15%GF增强，5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA66+30%GF+5%增韧剂","N6230SG","30%GF增强，5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"]],"apps":[["🚗","汽车零部件"],["🏋","运动器材"],["👶","婴儿童车结构件"],["🏋","电动工具"],["🔗","脚轮"],["🔗","扎带"]],"img":"images/product-pa.jpg"},
  'PA66 矿纤增强系列':{"sub":"PA66 矿纤增强系列 · N6215M · PA66+15%MF","meta":{"desc":"PA66+15%MF","model":"N6215M","feature":"15%矿物填充，表面优异，抗变形","apps":"汽车零部件，工业风扇，汽车散热风扇"},"intro":"Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["15%矿物填充","表面优异","抗变形"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA66+15%MF","N6215M","15%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，汽车散热风扇"],["PA66+30%MF","N6230M","30%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，汽车散热风扇"],["PA66+45%MF","N6245M","45%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，汽车散热风扇"],["PA66+15%MF+15%GF","N6215M3G","15%矿物填充，15%玻纤增强，尺寸安定","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩"]],"apps":[["🚗","汽车零部件"],["🔧","工业风扇"],["🚗","汽车散热风扇"]],"img":"images/product-pa.jpg"},
  'PA66 阻燃系列':{"sub":"PA66 阻燃系列 · NFB6200 · PA66 V0阻燃级","meta":{"desc":"PA66 V0阻燃级","model":"NFB6200","feature":"表面优异，流动性好","apps":"电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"},"intro":"Kitech高性能尼龙6.66复合材料系列 将高强度与外观性完美结合，兼具刚性与韧性的平衡，非常适用于动态性产品，如汽车零部件，运动器材，婴儿童车等结构部件的以塑代钢，轻量化的首选。选用进口国际大厂聚酰胺切片作为基材，潜心研究数十种高性能玻璃纤维，矿物纤维及填充剂的力学性能，分散效果，骨架作用，配以现代化高精度，高扭矩，双螺杆高速挤出系统，自主创新发明螺杆组合，采用科学挤出工艺，获得性能优异及稳定的产品组合，性能大幅度超越国内同类产品，优于国际品牌。Kitech针对动态性产品使用环境要求开发出具有耐高温、长期耐热稳定性、耐水解性、耐候性等特殊要求的产品规格，被广泛应用于汽车发动机周边，汽车水箱、空滤系统、进气歧管、发动机盖罩、后视镜骨架及各类汽车功能部件。","tags":["表面优异","流动性好"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["描述","典型规格","典型特点","典型应用"],["PA66 V0阻燃级","NFB6200","表面优异，流动性好","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA66+10-30%GF+V0 溴锑阻燃级","NFB6210G，NFB6230G","高强度阻燃材料，流动性佳，易脱模，适合薄壁产品","典型应用"],["PA66+10-30%GF+V0 红磷阻燃级","NFB6210G-P，NFB6230G-P","不含卤素与锑，低烟密度，CTI＞350V","典型应用"],["PA66+10-30%GF+V0 无卤阻燃级","NFB6210G-HF，NFB6230G-HF","不含卤素与锑，低比重，高强度，高白度，着色效果好，高CTI值＞500V，耐高压","典型应用"],["PA66+30%MF+V0阻燃级","NFB6230M","30%矿物增强，V0阻燃级","典型应用"]],"apps":[["⚡","电子电器"],["⚡","家用电器"],["⚡","线圈骨架"],["🚗","汽车零部件"],["🚗","汽车散热风扇"],["⚡","连接器"]],"img":"images/product-pa.jpg"},
  '无填充聚丙烯系列':{"sub":"无填充聚丙烯系列 · P6100R · PP低温耐寒级","meta":{"desc":"PP低温耐寒级","model":"P6100R","feature":"高熔指，高抗冲，低温耐寒","apps":"汽车零部件，婴儿童车，运动器材，日用品"},"intro":"Kitech高性能聚丙烯复合材料 优选国际大厂基材及性能优异的填充添加剂，大幅度改善聚丙烯材料收缩率及机械性能。开发出新材料具有刚韧平衡，优异的耐老化性能及良好加工性。针对汽车零部件产品，Kitech聚丙烯复合材料更具有低VOC，超高流动性，优秀的抗冲击强度及高弯曲模量，良好的着色性等特点，被广泛运用于汽车保险杠，仪表盘，门板配件，中控扶手盖，立柱，天窗配件、座椅护板，儿童安全座椅本体等汽车内外饰件中。","tags":["高熔指","高抗冲","低温耐寒"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PP低温耐寒级","P6100R","高熔指，高抗冲，低温耐寒","汽车零部件，婴儿童车，运动器材，日用品"],["PP抗翘曲变形级","P6100H","超高熔指，抗翘曲变形，透明性优","汽车零部件，婴儿童车，运动器材，日用品"],["PP超低温耐寒级","P6100R-E","超高抗冲，延伸率高，低温耐寒","汽车零部件，运动器材，溜冰鞋，滑板车"],["PP抗反白级","P6100A","高抗冲，抗发白，低温耐寒","婴儿童车，运动器材，日用品"]],"apps":[["🚗","汽车零部件"],["👶","婴儿童车"],["🏋","运动器材"],["🔧","日用品"]],"img":"images/product-pp.webp"},
  '玻纤增强聚丙烯系列':{"sub":"玻纤增强聚丙烯系列 · P6110G · PP+10%GF","meta":{"desc":"PP+10%GF","model":"P6110G","feature":"10%GF增强，抗冲性优","apps":"运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"},"intro":"Kitech高性能聚丙烯复合材料 优选国际大厂基材及性能优异的填充添加剂，大幅度改善聚丙烯材料收缩率及机械性能。开发出新材料具有刚韧平衡，优异的耐老化性能及良好加工性。针对汽车零部件产品，Kitech聚丙烯复合材料更具有低VOC，超高流动性，优秀的抗冲击强度及高弯曲模量，良好的着色性等特点，被广泛运用于汽车保险杠，仪表盘，门板配件，中控扶手盖，立柱，天窗配件、座椅护板，儿童安全座椅本体等汽车内外饰件中。","tags":["10%GF增强","抗冲性优"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PP+10%GF","P6110G","10%GF增强，抗冲性优","运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"],["PP+15%GF","P6115G","15%GF增强，抗冲性优","运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"],["PP+30%GF","P6130G","30%GF增强，弯曲强度优","运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"],["PP+40%GF","P6140G","40%GF增强，尺寸安定性好","运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"]],"apps":[["🏋","运动器材"],["🚗","汽车零部件"],["⚡","家用电器"],["🔧","船桨"],["🔧","办公家具"],["🔧","水泵配件"]],"img":"images/product-pp.webp"},
  '矿物填充聚丙烯系列':{"sub":"矿物填充聚丙烯系列 · P6115M · PP+15%MF","meta":{"desc":"PP+15%MF","model":"P6115M","feature":"15%矿物增强，表面性优","apps":"水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"},"intro":"Kitech高性能聚丙烯复合材料 优选国际大厂基材及性能优异的填充添加剂，大幅度改善聚丙烯材料收缩率及机械性能。开发出新材料具有刚韧平衡，优异的耐老化性能及良好加工性。针对汽车零部件产品，Kitech聚丙烯复合材料更具有低VOC，超高流动性，优秀的抗冲击强度及高弯曲模量，良好的着色性等特点，被广泛运用于汽车保险杠，仪表盘，门板配件，中控扶手盖，立柱，天窗配件、座椅护板，儿童安全座椅本体等汽车内外饰件中。","tags":["15%矿物增强","表面性优"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PP+15%MF","P6115M","15%矿物增强，表面性优","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"],["PP+20%MF","P6120M","20%矿物增强，尺寸稳定","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"],["PP+30%MF","P6130M","30%矿物增强，抗收缩性好","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"],["PP+20%MF+UV","P6120M-UV","20%矿物增强，耐候耐黄变","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"],["PP+20%MF+UV+抗菌","P6120MUV-J","20%矿物增强，高亮表面，抗菌","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"]],"apps":[["🔧","水浴配件"],["🔧","水泵配件"],["⚡","家用电器"],["🔧","厨卫用品"],["🚗","汽车配件"],["🔧","家具配件"]],"img":"images/product-pp.webp"},
  '阻燃聚丙烯系列':{"sub":"阻燃聚丙烯系列 · PFB6100 · PP阻燃V0级（不滴落）","meta":{"desc":"PP阻燃V0级（不滴落）","model":"PFB6100","feature":"表面性优异，阻燃V0级","apps":"家用电器，电子产品，电池外壳"},"intro":"Kitech高性能聚丙烯复合材料 优选国际大厂基材及性能优异的填充添加剂，大幅度改善聚丙烯材料收缩率及机械性能。开发出新材料具有刚韧平衡，优异的耐老化性能及良好加工性。针对汽车零部件产品，Kitech聚丙烯复合材料更具有低VOC，超高流动性，优秀的抗冲击强度及高弯曲模量，良好的着色性等特点，被广泛运用于汽车保险杠，仪表盘，门板配件，中控扶手盖，立柱，天窗配件、座椅护板，儿童安全座椅本体等汽车内外饰件中。","tags":["表面性优异","阻燃V0级"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PP阻燃V0级（不滴落）","PFB6100","表面性优异，阻燃V0级","家用电器，电子产品，电池外壳"],["PP阻燃V0级（滴落型）","PFB6200","优异的表面光泽度，高流动，高冲击，低比重","家用电器，电子产品，电池外壳"]],"apps":[["⚡","家用电器"],["⚡","电子产品"],["🔧","电池外壳"]],"img":"images/product-pp.webp"},
  '抗静电聚丙烯系列':{"sub":"抗静电聚丙烯系列 · P6110CTBK · 抗静电PP","meta":{"desc":"抗静电PP","model":"P6110CTBK","feature":"高流动，高冲击，表面电阻10的6-10次方","apps":"导电球，移液管，电子托盘"},"intro":"Kitech高性能复合材料系列：抗静电PP，高流动，高冲击，表面电阻10的6-10次方，应用于导电球，移液管，电子托盘。","tags":["高流动","高冲击","表面电阻10的6-10次方"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["抗静电PP","P6110CTBK","高流动，高冲击，表面电阻10的6-10次方","导电球，移液管，电子托盘"],["导电PP","P6120CTBK","高流动，高冲击，表面电阻10的3-4次方","导电球，移液管，电子托盘"]],"apps":[["🔧","导电球"],["⚡","移液管"],["⚡","电子托盘"]],"img":"images/product-pp.webp"},
  '口罩专用料（高熔指熔喷材料）':{"sub":"口罩专用料（高熔指熔喷材料） · P6100A15 · 1500聚丙烯熔喷布专用料","meta":{"desc":"1500聚丙烯熔喷布专用料","model":"P6100A15","feature":"稳定的流动性，灰分低、分子量分布窄","apps":"口罩专用熔喷布"},"intro":"稳定MFI：1540g/10min (GB/T3682.1-2018) 高MFI降低熔喷能耗，提高产能，适合熔喷工艺较弱的热空气流牵伸作用 专业MFR/MVR熔指仪过程检测，SPC严格控制在±50 挤出机熔压、电流及时监控，保障材料均一性，稳定性 成拼AB桶双批混，成品再次均化稳定 超低灰分ash：≤180ppm （GB/T9345-1998） 低气味、超低灰分、有效延长熔喷模头清理切换周期 高洁净高流动性PP原料 进口低味过氧化物交联剂，双真空除味 超细挤出过滤网、高扭矩、高长径比，挤出机 分子量分布MWD:分子量分布窄2-4(GPC) 便于加工出超细纤维0.5-5μm,等规度≥97%。 组分失重称精准控制过氧化物交联添加量 二次挤出MFI无变化确保挤出反应完全充分 超强定制进口挤出螺纹分散原件/ZME/TME齿形盘","tags":["稳定的流动性","灰分低","分子量分布窄"],"specsHead":["产品描述","型号","材料特性","应用领域","技术资料"],"specs":[["1500聚丙烯熔喷布专用料","P6100A15","稳定的高流动性，低碳、环保无毒， 分子量分布窄、 灰分低， 低VOC、无其他产物残留、手感柔软","口罩专用熔喷布","物性表 FDA测试报告 高熔指测试报告"],["1500聚丙烯熔喷布专用料 含驻极母粒","P6100A150Z","稳定的高流动性、低碳、环保无毒， 分子量分布窄、灰分低， 低VOC、 无其他产物残留、手感柔软","KN90/KN95/KN99 口罩专用熔喷布"],["熔喷布高效静电驻极母粒","P6100ZJ","驻留静电荷，提升滤效； 高效、低阻力、不堵孔","熔喷布专用静电驻极"],["无纺布专用纺粘料","P6100F","出丝均匀，高延伸性，力学性能优","口罩内外层无纺布"]],"apps":[["😷","口罩专用熔喷布"]],"img":"images/product-pp.webp"},
  'PC/ABS 合金系列':{"sub":"PC/ABS 合金系列 · CA6130 · PC/ABS合金（3:7）","meta":{"desc":"PC/ABS合金（3:7）","model":"CA6130","feature":"表面优异，抗冲性好，光泽度优","apps":"汽车内外饰，家用电器，3C数码"},"intro":"Kitech合金系列 具有优异的机械性能，良好的常温，低温抗冲击强度，光泽度优，加工性好，耐候耐变色等特点，主要应用于汽车空调出风口，中控面板，后视镜外罩，门把手外罩，格栅，扰流板等汽车零部件。","tags":["表面优异","抗冲性好","光泽度优"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PC/ABS合金（3:7）","CA6130","表面优异，抗冲性好，易成型","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/ABS合金（5:5）","CA6150","表面优异，抗冲性好，光泽度优","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/ABS合金（6:4）","CA6160","表面优异，抗冲性好，高耐热","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/ABS合金阻燃V0级","CAFB6050","表面优异，抗冲性好，光泽度优","汽车零部件，劳保用品，头盔，智能穿戴配件"]],"apps":[["🚗","汽车内外饰"],["⚡","家用电器"],["🔧","3C数码"]],"img":"images/product-pcabs.webp"},
  'PC/PBT 合金系列':{"sub":"PC/PBT 合金系列 · CB6130 · PC/PBT合金（3:7）","meta":{"desc":"PC/PBT合金（3:7）","model":"CB6130","feature":"表面性好，耐候性优","apps":"汽车零部件，劳保用品，头盔，智能穿戴配件"},"intro":"Kitech合金系列 具有优异的机械性能，良好的常温，低温抗冲击强度，光泽度优，加工性好，耐候耐变色等特点，主要应用于汽车空调出风口，中控面板，后视镜外罩，门把手外罩，格栅，扰流板等汽车零部件。","tags":["表面性好","耐候性优"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PC/PBT合金（3:7）","CB6130","表面性好，耐候性优","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/PBT合金（5:5）","CB6150","表面性好，耐候性优","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/PBT合金（6:4）","CB6160","表面性好，耐候性优","汽车零部件，劳保用品，头盔，智能穿戴配件"]],"apps":[["🚗","汽车零部件"],["🔧","劳保用品"],["🔧","头盔"],["🔧","智能穿戴配件"]],"img":"images/product-pcabs.webp"},
  'PA6/PA66 合金':{"sub":"PA6/PA66 合金 · N6600 · PA6/PA66合金","meta":{"desc":"PA6/PA66合金","model":"N6600","feature":"综合机械性能好","apps":"汽车零部件，婴儿童车"},"intro":"Kitech合金系列 具有优异的机械性能，良好的常温，低温抗冲击强度，光泽度优，加工性好，耐候耐变色等特点，主要应用于汽车空调出风口，中控面板，后视镜外罩，门把手外罩，格栅，扰流板等汽车零部件。","tags":["综合机械性能好"],"specsHead":["项目","内容"],"specs":[["描述","PA6/PA66合金"],["典型规格","N6600"],["典型特点","综合机械性能好"],["典型应用","汽车零部件，婴儿童车"]],"apps":[["🚗","汽车零部件"],["👶","婴儿童车"]],"img":"images/product-pcabs.webp"},
  'PA 长玻纤增强系列':{"sub":"PA 长玻纤增强系列 · N6130LG · PA6+30%LFT","meta":{"desc":"PA6+30%LFT","model":"N6130LG","feature":"高弯曲模量，高抗冲","apps":"汽车零部件，运动器材，户外产品"},"intro":"Kitech长玻纤增强复合材料 基于先进的加工设备及混炼挤出技术，结合高性能玻璃纤维材料，应用前沿的玻纤分散剂交联技术，获得业内领先的长玻纤增强尼龙及聚丙烯材料。该系列产品具有高机械强度，高模量，低收缩率，良好的耐热性及耐候性等特点，是理想的以塑代钢材料，被广泛用于汽车前段模块，油门踏板基座，后视镜基座，电池支架、门板框架及滑板车底座，儿童汽车安全座椅内部骨架等结构件。","tags":["高弯曲模量","高抗冲"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PA6+30%LFT","N6130LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"],["PA6+40%LFT","N6140LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"],["PA6+50%LFT","N6150LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"]],"apps":[["🚗","汽车零部件"],["🏋","运动器材"],["🔧","户外产品"]],"img":"images/product-lft.webp"},
  'PP 长玻纤增强系列':{"sub":"PP 长玻纤增强系列 · P6130LG · PP+30%LFT","meta":{"desc":"PP+30%LFT","model":"P6130LG","feature":"高弯曲模量，高抗冲","apps":"汽车零部件，运动器材，户外产品"},"intro":"Kitech长玻纤增强复合材料 基于先进的加工设备及混炼挤出技术，结合高性能玻璃纤维材料，应用前沿的玻纤分散剂交联技术，获得业内领先的长玻纤增强尼龙及聚丙烯材料。该系列产品具有高机械强度，高模量，低收缩率，良好的耐热性及耐候性等特点，是理想的以塑代钢材料，被广泛用于汽车前段模块，油门踏板基座，后视镜基座，电池支架、门板框架及滑板车底座，儿童汽车安全座椅内部骨架等结构件。","tags":["高弯曲模量","高抗冲"],"specsHead":["描述","典型规格","典型特点","典型应用"],"specs":[["PP+30%LFT","P6130LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"],["PP+40%LFT","P6140LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"],["PP+50%LFT","P6150LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"]],"apps":[["🚗","汽车零部件"],["🏋","运动器材"],["🔧","户外产品"]],"img":"images/product-lft.webp"},
  'PPS 系列':{"sub":"PPS 系列 · PPS6140G · PPS+40%GF","meta":{"desc":"PPS+40%GF","model":"PPS6140G","feature":"40%GF增强，高弯曲模量，耐热性优","apps":"汽车零部件，充电枪，电子电器"},"intro":"Kitech拥有省级工程技术研发中心及省级企业技术中心等创新研发平台，拥有众多经验丰富的材料研发工程师，为客户实现材料定制，制件优化，性能改善等客制化服务。借助Kitech塑胶成型一体化专业服务平台，解决塑胶成型技术分散，开发效率低下等行业痛点，同时Kitech研发团队致力于研究环境友好型，功能性的高性能高分子复合新材料，为实现以塑代钢，以塑代木这种节能环保生产消费新趋势贡献力量","tags":["40%GF增强","高弯曲模量","耐热性优"],"specsHead":["项目","内容"],"specs":[["描述","PPS+40%GF"],["典型规格","PPS6140G"],["典型特点","40%GF增强，高弯曲模量，耐热性优"],["典型应用","汽车零部件，充电枪，电子电器"]],"apps":[["🚗","汽车零部件"],["🔧","充电枪"],["⚡","电子电器"]],"img":"images/product-cf.webp"},
  'PPO 系列':{"sub":"PPO 系列 · PPO6120G · PPO+20%GF","meta":{"desc":"PPO+20%GF","model":"PPO6120G","feature":"20%GF增强，尺寸安定性优","apps":"水浴配件，水泵配件，家用电器"},"intro":"Kitech拥有省级工程技术研发中心及省级企业技术中心等创新研发平台，拥有众多经验丰富的材料研发工程师，为客户实现材料定制，制件优化，性能改善等客制化服务。借助Kitech塑胶成型一体化专业服务平台，解决塑胶成型技术分散，开发效率低下等行业痛点，同时Kitech研发团队致力于研究环境友好型，功能性的高性能高分子复合新材料，为实现以塑代钢，以塑代木这种节能环保生产消费新趋势贡献力量","tags":["20%GF增强","尺寸安定性优"],"specsHead":["项目","内容"],"specs":[["描述","PPO+20%GF"],["典型规格","PPO6120G"],["典型特点","20%GF增强，尺寸安定性优"],["典型应用","水浴配件，水泵配件，家用电器"]],"apps":[["🔧","水浴配件"],["🔧","水泵配件"],["⚡","家用电器"]],"img":"images/product-cf.webp"},
  'TPR 系列':{"sub":"TPR 系列 · R6060A-UV · 抗黄变级","meta":{"desc":"抗黄变级","model":"R6060A-UV","feature":"抗黄变，耐候性优","apps":"手把包胶，工业脚轮，缓冲脚垫"},"intro":"Kitech拥有省级工程技术研发中心及省级企业技术中心等创新研发平台，拥有众多经验丰富的材料研发工程师，为客户实现材料定制，制件优化，性能改善等客制化服务。借助Kitech塑胶成型一体化专业服务平台，解决塑胶成型技术分散，开发效率低下等行业痛点，同时Kitech研发团队致力于研究环境友好型，功能性的高性能高分子复合新材料，为实现以塑代钢，以塑代木这种节能环保生产消费新趋势贡献力量","tags":["抗黄变","耐候性优"],"specsHead":["项目","内容"],"specs":[["描述","抗黄变级"],["典型规格","R6060A-UV"],["典型特点","抗黄变，耐候性优"],["典型应用","手把包胶，工业脚轮，缓冲脚垫"]],"apps":[["🔧","手把包胶"],["🔗","工业脚轮"],["🔧","缓冲脚垫"]],"img":"images/product-cf.webp"},
  'TPU 系列':{"sub":"TPU 系列 · R6060U · 耐磨级","meta":{"desc":"耐磨级","model":"R6060U","feature":"回弹性优，耐磨性好","apps":"鞋材，电动工具，工业脚轮"},"intro":"Kitech拥有省级工程技术研发中心及省级企业技术中心等创新研发平台，拥有众多经验丰富的材料研发工程师，为客户实现材料定制，制件优化，性能改善等客制化服务。借助Kitech塑胶成型一体化专业服务平台，解决塑胶成型技术分散，开发效率低下等行业痛点，同时Kitech研发团队致力于研究环境友好型，功能性的高性能高分子复合新材料，为实现以塑代钢，以塑代木这种节能环保生产消费新趋势贡献力量","tags":["回弹性优","耐磨性好"],"specsHead":["项目","内容"],"specs":[["描述","耐磨级"],["典型规格","R6060U"],["典型特点","回弹性优，耐磨性好"],["典型应用","鞋材，电动工具，工业脚轮"]],"apps":[["🔧","鞋材"],["🏋","电动工具"],["🔗","工业脚轮"]],"img":"images/product-cf.webp"},
  '免喷涂系列':{"sub":"免喷涂系列 · 按客户需求定制 · 按客户需求定制","meta":{"desc":"按客户需求定制","model":"按客户需求定制","feature":"表面性优，光泽度好，流动性好","apps":"汽车零部件，家用电器外壳，各类装饰件"},"intro":"Kitech拥有省级工程技术研发中心及省级企业技术中心等创新研发平台，拥有众多经验丰富的材料研发工程师，为客户实现材料定制，制件优化，性能改善等客制化服务。借助Kitech塑胶成型一体化专业服务平台，解决塑胶成型技术分散，开发效率低下等行业痛点，同时Kitech研发团队致力于研究环境友好型，功能性的高性能高分子复合新材料，为实现以塑代钢，以塑代木这种节能环保生产消费新趋势贡献力量","tags":["表面性优","光泽度好","流动性好"],"specsHead":["项目","内容"],"specs":[["描述","按客户需求定制"],["典型规格","按客户需求定制"],["典型特点","按客户需求定制"],["典型应用","汽车零部件，家用电器外壳，各类装饰件"]],"apps":[["🚗","汽车零部件"],["⚡","家用电器外壳"],["🔧","各类装饰件"]],"img":"images/product-cf.webp"},
  'PA6 Unfilled Series':{"sub":"PA6 Unfilled Series · N6100 · General injection grade","meta":{"desc":"General injection grade","model":"N6100","feature":"General purpose · high flow · weather & yellowing resistant","apps":"Electronics, connectors, general industrial parts, cable ties, clips, toys"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["General","purpose","high","flow","weather"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["一般注塑级","N6100","通用级","电子电器，电子接插件，一般工业结构件，尼龙扎带，卡扣，玩具"],["脱模改善级","N6100H","高流动，脱模改善，自润滑","电子电器，线圈骨架，电器外壳"],["耐候级","N6100-UV","耐候，耐黄变","电器外壳，户外产品"]],"apps":[["🔧","Electronics"],["🔧","connectors"],["🔧","general industrial parts"],["🔧","cable ties"],["🔧","clips"],["🔧","toys"]],"img":"images/product-pa.jpg"},
  'PA6 Glass-fiber Reinforced Series':{"sub":"PA6 Glass-fiber Reinforced Series · N6110G · PA6 + glass fiber","meta":{"desc":"PA6 + glass fiber","model":"N6110G","feature":"High strength · high rigidity","apps":"Automotive structural parts, sports equipment, power tool housings, gears"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["High","strength","high","rigidity"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA6+10%GF","N6110G","10%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA6+15%GF","N6115G","15%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA6+30%GF","N6130G","30%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA6+50%GF","N6150G","50%GF增强，超高弯曲模量","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA6+60%GF","N6160G","60%GF增强，超高弯曲模量","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"]],"apps":[["🔧","Automotive structural parts"],["🔧","sports equipment"],["🔧","power tool housings"],["🔧","gears"]],"img":"images/product-pa.jpg"},
  'PA6 Toughened Cold-resistant Series':{"sub":"PA6 Toughened Cold-resistant Series · — · Toughened cold-resistant PA6","meta":{"desc":"Toughened cold-resistant PA6","model":"—","feature":"Ultra-low-temperature toughening","apps":"Automotive parts, outdoor equipment, cold-environment structural parts"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["Ultra-low-temperature","toughening"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA6+5%增韧剂","N6110R","5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA6+10%增韧剂","N6120R","10%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA6+15%GF+5%增韧剂","N6115SG","15%GF增强，5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA6+30%GF+5%增韧剂","N6130SG","30%GF增强，5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"]],"apps":[["🔧","Automotive parts"],["🔧","outdoor equipment"],["🔧","cold-environment structural parts"]],"img":"images/product-pa.jpg"},
  'PA6 Mineral-fiber Reinforced Series':{"sub":"PA6 Mineral-fiber Reinforced Series · — · Mineral-fiber reinforced PA6","meta":{"desc":"Mineral-fiber reinforced PA6","model":"—","feature":"Dimensional stability · low warpage","apps":"Automotive functional parts, appliance housings, precision parts"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["Dimensional","stability","low","warpage"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA6+10%MF","N6110M","10%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩，电器底座，隔热条，轮毂盖"],["PA6+15%MF","N6115M","15%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩，电器底座，隔热条，轮毂盖"],["PA6+30%MF","N6130M","30%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩，电器底座，隔热条，轮毂盖"],["PA6+20%MF+10%GF","N6120M2G","20%矿物填充，10%玻纤增强，尺寸安定","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩"],["PA6+25%MF+15%GF","N6125M3G","25%矿物填充，15%玻纤增强，尺寸安定","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩"]],"apps":[["🔧","Automotive functional parts"],["🔧","appliance housings"],["🔧","precision parts"]],"img":"images/product-pa.jpg"},
  'PA6 Carbon-fiber Reinforced Series':{"sub":"PA6 Carbon-fiber Reinforced Series · — · Carbon-fiber reinforced PA6","meta":{"desc":"Carbon-fiber reinforced PA6","model":"—","feature":"Light & strong · conductive","apps":"Premium sports equipment, UAVs, precision instruments"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["Light","&","strong","conductive"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA6+15%TF","N6115T","10%碳纤增强，超高弯曲强度","车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"],["PA6+30%TF","N6130T","30%碳纤增强，超高弯曲强度","车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"],["PA6+45%TF","N6145T","45%碳纤增强，超高弯曲强度","车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"],["PA6+15%TF+15%GF","N6115T3G","15%碳纤增强，15%玻纤增强","车零部件，运动器材，工业产品结构件，无人机浆叶，导电结构件"]],"apps":[["🔧","Premium sports equipment"],["🔧","UAVs"],["🔧","precision instruments"]],"img":"images/product-pa.jpg"},
  'PA6 Flame-retardant Series':{"sub":"PA6 Flame-retardant Series · — · Halogen-free FR PA6","meta":{"desc":"Halogen-free FR PA6","model":"—","feature":"Halogen-free flame retardant V0","apps":"NEV battery distribution boxes, electronic safety parts"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["Halogen-free","flame","retardant","V0"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA6 V0阻燃级","NFB6100","表面优异，流动性好","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA6+10-30%GF+V0 溴锑阻燃级","NFB6110G，NFB6130G","高强度阻燃材料，流动性佳，易脱模，适合薄壁产品","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA6+10-30%GF+V0 红磷阻燃级","NFB6110G-P，NFB6130G-P","不含卤素与锑，低烟密度，CTI＞350V","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA6+10-30%GF+V0 无卤阻燃级","NFB6110G-HF，NFB6130G-HF","不含卤素与锑，低比重，高强度，高白度，着色效果好，高CTI值＞500V，耐高压","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA6+30%MF+V0阻燃级","NFB6130M","30%矿物增强，V0阻燃级","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"]],"apps":[["🔧","NEV battery distribution boxes"],["🔧","electronic safety parts"]],"img":"images/product-pa.jpg"},
  'PA6 Other Series':{"sub":"PA6 Other Series · — · Custom PA6 grades","meta":{"desc":"Custom PA6 grades","model":"—","feature":"Customized","apps":"Per customer requirements"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["Customized"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA6+30%GF 热稳定级","N6130G-HS","30%GF增强，热稳定性优","汽车发动机周边，散热风扇，电子电器"],["PA6+30%GF 耐水解级","N6130G-WS","30%GF增强，耐水解性优","汽车水箱配件，水泵配件，水浴配件"],["PA6+30%GF 高模量级","N6130GBKV","30%GF增强，超高抗冲击模量","婴儿童车结构件，运动器材结构件"],["PA6+30%GF 热稳定级","N6130G-HS","30%GF增强，热稳定性优","汽车发动机周边，散热风扇，电子电器"]],"apps":[["🔧","Per customer requirements"]],"img":"images/product-pa.jpg"},
  'PA66 Unfilled Series':{"sub":"PA66 Unfilled Series · N6600 · General injection grade PA66","meta":{"desc":"General injection grade PA66","model":"N6600","feature":"Higher strength · higher heat resistance","apps":"Electronics, connectors, industrial parts, cable ties, clips, toys"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["Higher","strength","higher","heat","resistance"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["一般注塑级","N6200","通用级","电子电器，电子接插件，一般工业结构件，卡扣，玩具"],["脱模改善级","N6200H","高流动，脱模改善，自润滑","电子电器，线圈骨架，电器外壳，汽车扎带"],["耐候级","N6200-UV","耐候，耐黄变","电子电器，户外用品"]],"apps":[["🔧","Electronics"],["🔧","connectors"],["🔧","industrial parts"],["🔧","cable ties"],["🔧","clips"],["🔧","toys"]],"img":"images/product-pa.jpg"},
  'PA66 Glass-fiber Reinforced Series':{"sub":"PA66 Glass-fiber Reinforced Series · — · PA66 + glass fiber","meta":{"desc":"PA66 + glass fiber","model":"—","feature":"High strength · high rigidity · heat resistant","apps":"Automotive structural parts, sports equipment, power tools"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["High","strength","high","rigidity","heat"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA66+10%GF","N6210G","10%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA66+15%GF","N6215G","15%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA66+30%GF","N6230G","30%GF增强，优异机械性能","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"],["PA66+50%GF","N6250G","50%GF增强，超高弯曲模量","汽车零部件，运动器材，婴儿童车结构件，电动工具，办公家具，小家电外壳，齿轮，水泵壳体，卫浴配件，工业散热系统"]],"apps":[["🔧","Automotive structural parts"],["🔧","sports equipment"],["🔧","power tools"]],"img":"images/product-pa.jpg"},
  'PA66 Toughened Cold-resistant Series':{"sub":"PA66 Toughened Cold-resistant Series · — · Toughened cold-resistant PA66","meta":{"desc":"Toughened cold-resistant PA66","model":"—","feature":"Low-temperature toughening","apps":"Automotive parts, outdoor equipment"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["Low-temperature","toughening"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA66+5%增韧剂","N6210R","5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA66+10%增韧剂","N6220R","10%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA66+15%GF+5%增韧剂","N6215SG","15%GF增强，5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"],["PA66+30%GF+5%增韧剂","N6230SG","30%GF增强，5%增韧剂，低温耐寒","汽车零部件，运动器材，婴儿童车结构件，电动工具，脚轮，扎带，卡扣，厨具"]],"apps":[["🔧","Automotive parts"],["🔧","outdoor equipment"]],"img":"images/product-pa.jpg"},
  'PA66 Mineral-fiber Reinforced Series':{"sub":"PA66 Mineral-fiber Reinforced Series · — · Mineral-fiber reinforced PA66","meta":{"desc":"Mineral-fiber reinforced PA66","model":"—","feature":"Dimensional stability · low warpage","apps":"Automotive functional parts, precision parts"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["Dimensional","stability","low","warpage"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA66+15%MF","N6215M","15%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，汽车散热风扇"],["PA66+30%MF","N6230M","30%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，汽车散热风扇"],["PA66+45%MF","N6245M","45%矿物填充，表面优异，抗变形","汽车零部件，工业风扇，汽车散热风扇"],["PA66+15%MF+15%GF","N6215M3G","15%矿物填充，15%玻纤增强，尺寸安定","汽车零部件，工业风扇，电器结构件，汽车发动机盖罩"]],"apps":[["🔧","Automotive functional parts"],["🔧","precision parts"]],"img":"images/product-pa.jpg"},
  'PA66 Flame-retardant Series':{"sub":"PA66 Flame-retardant Series · — · Flame-retardant PA66","meta":{"desc":"Flame-retardant PA66","model":"—","feature":"FR V0 for safety-critical parts","apps":"NEV battery boxes, electronic safety parts"},"intro":"Qide Kitech high-performance nylon 6/66 composites combine high strength with excellent appearance, balancing rigidity and toughness for dynamic products such as automotive parts, sports equipment and strollers — the preferred choice for plastic-for-steel lightweighting. Made with imported premium polyamide chips, modern high-torque twin-screw extrusion and self-developed screw combinations, they deliver stable, high-performance grades surpassing domestic peers.","tags":["FR","V0","for","safety-critical","parts"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["描述","典型规格","典型特点","典型应用"],["PA66 V0阻燃级","NFB6200","表面优异，流动性好","电子电器，家用电器，线圈骨架，汽车零部件，汽车散热风扇，连接器，低压电器外壳"],["PA66+10-30%GF+V0 溴锑阻燃级","NFB6210G，NFB6230G","高强度阻燃材料，流动性佳，易脱模，适合薄壁产品","典型应用"],["PA66+10-30%GF+V0 红磷阻燃级","NFB6210G-P，NFB6230G-P","不含卤素与锑，低烟密度，CTI＞350V","典型应用"],["PA66+10-30%GF+V0 无卤阻燃级","NFB6210G-HF，NFB6230G-HF","不含卤素与锑，低比重，高强度，高白度，着色效果好，高CTI值＞500V，耐高压","典型应用"],["PA66+30%MF+V0阻燃级","NFB6230M","30%矿物增强，V0阻燃级","典型应用"]],"apps":[["🔧","NEV battery boxes"],["🔧","electronic safety parts"]],"img":"images/product-pa.jpg"},
  'Unfilled PP Series':{"sub":"Unfilled PP Series · — · General injection grade PP","meta":{"desc":"General injection grade PP","model":"—","feature":"Lightweight · general purpose","apps":"Household goods, packaging, general industrial parts"},"intro":"Qide Kitech high-performance polypropylene composites use premium base resin and high-performance additives to greatly improve shrinkage and mechanical properties, with balanced rigidity and toughness, excellent aging resistance and good processability. For automotive applications they offer low VOC, high flow, high impact strength and flexural modulus, widely used in bumpers, instrument panels, door panels and other interior/exterior parts.","tags":["Lightweight","general","purpose"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PP低温耐寒级","P6100R","高熔指，高抗冲，低温耐寒","汽车零部件，婴儿童车，运动器材，日用品"],["PP抗翘曲变形级","P6100H","超高熔指，抗翘曲变形，透明性优","汽车零部件，婴儿童车，运动器材，日用品"],["PP超低温耐寒级","P6100R-E","超高抗冲，延伸率高，低温耐寒","汽车零部件，运动器材，溜冰鞋，滑板车"],["PP抗反白级","P6100A","高抗冲，抗发白，低温耐寒","婴儿童车，运动器材，日用品"]],"apps":[["🔧","Household goods"],["🔧","packaging"],["🔧","general industrial parts"]],"img":"images/product-pp.webp"},
  'Glass-fiber Reinforced PP Series':{"sub":"Glass-fiber Reinforced PP Series · — · PP + glass fiber","meta":{"desc":"PP + glass fiber","model":"—","feature":"Rigid & tough · low odor","apps":"Automotive interior/exterior parts, appliance structural parts"},"intro":"Qide Kitech high-performance polypropylene composites use premium base resin and high-performance additives to greatly improve shrinkage and mechanical properties, with balanced rigidity and toughness, excellent aging resistance and good processability. For automotive applications they offer low VOC, high flow, high impact strength and flexural modulus, widely used in bumpers, instrument panels, door panels and other interior/exterior parts.","tags":["Rigid","&","tough","low","odor"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PP+10%GF","P6110G","10%GF增强，抗冲性优","运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"],["PP+15%GF","P6115G","15%GF增强，抗冲性优","运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"],["PP+30%GF","P6130G","30%GF增强，弯曲强度优","运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"],["PP+40%GF","P6140G","40%GF增强，尺寸安定性好","运动器材，汽车零部件，家用电器，船桨，办公家具，水泵配件，滑板车配件 上下无产品链接"]],"apps":[["🔧","Automotive interior/exterior parts"],["🔧","appliance structural parts"]],"img":"images/product-pp.webp"},
  'Mineral-filled PP Series':{"sub":"Mineral-filled PP Series · — · Mineral-filled PP","meta":{"desc":"Mineral-filled PP","model":"—","feature":"Dimensional stability · low cost","apps":"Automotive parts, appliance housings"},"intro":"Qide Kitech high-performance polypropylene composites use premium base resin and high-performance additives to greatly improve shrinkage and mechanical properties, with balanced rigidity and toughness, excellent aging resistance and good processability. For automotive applications they offer low VOC, high flow, high impact strength and flexural modulus, widely used in bumpers, instrument panels, door panels and other interior/exterior parts.","tags":["Dimensional","stability","low","cost"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PP+15%MF","P6115M","15%矿物增强，表面性优","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"],["PP+20%MF","P6120M","20%矿物增强，尺寸稳定","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"],["PP+30%MF","P6130M","30%矿物增强，抗收缩性好","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"],["PP+20%MF+UV","P6120M-UV","20%矿物增强，耐候耐黄变","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"],["PP+20%MF+UV+抗菌","P6120MUV-J","20%矿物增强，高亮表面，抗菌","水浴配件，水泵配件，家用电器，厨卫用品，汽车配件，家具配件"]],"apps":[["🔧","Automotive parts"],["🔧","appliance housings"]],"img":"images/product-pp.webp"},
  'Flame-retardant PP Series':{"sub":"Flame-retardant PP Series · — · Flame-retardant PP","meta":{"desc":"Flame-retardant PP","model":"—","feature":"FR V0 · high GWIT","apps":"Appliance housings, power parts, sockets"},"intro":"Qide Kitech high-performance polypropylene composites use premium base resin and high-performance additives to greatly improve shrinkage and mechanical properties, with balanced rigidity and toughness, excellent aging resistance and good processability. For automotive applications they offer low VOC, high flow, high impact strength and flexural modulus, widely used in bumpers, instrument panels, door panels and other interior/exterior parts.","tags":["FR","V0","high","GWIT"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PP阻燃V0级（不滴落）","PFB6100","表面性优异，阻燃V0级","家用电器，电子产品，电池外壳"],["PP阻燃V0级（滴落型）","PFB6200","优异的表面光泽度，高流动，高冲击，低比重","家用电器，电子产品，电池外壳"]],"apps":[["🔧","Appliance housings"],["🔧","power parts"],["🔧","sockets"]],"img":"images/product-pp.webp"},
  'Antistatic PP Series':{"sub":"Antistatic PP Series · — · Antistatic PP","meta":{"desc":"Antistatic PP","model":"—","feature":"Antistatic","apps":"Electronic housings, dust-free & ESD-safe parts"},"intro":"Qide Kitech high-performance polypropylene composites use premium base resin and high-performance additives to greatly improve shrinkage and mechanical properties, with balanced rigidity and toughness, excellent aging resistance and good processability. For automotive applications they offer low VOC, high flow, high impact strength and flexural modulus, widely used in bumpers, instrument panels, door panels and other interior/exterior parts.","tags":["Antistatic"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["抗静电PP","P6110CTBK","高流动，高冲击，表面电阻10的6-10次方","导电球，移液管，电子托盘"],["导电PP","P6120CTBK","高流动，高冲击，表面电阻10的3-4次方","导电球，移液管，电子托盘"]],"apps":[["🔧","Electronic housings"],["🔧","dust-free & ESD-safe parts"]],"img":"images/product-pp.webp"},
  'Mask-grade Material (High-MFI Melt-blown)':{"sub":"Mask-grade Material (High-MFI Melt-blown) · — · Melt-blown / spunbond grade","meta":{"desc":"Melt-blown / spunbond grade","model":"—","feature":"High MFI · low ash · low odor","apps":"Medical masks, melt-blown & spunbond fabrics"},"intro":"Qide Kitech high-performance polypropylene composites use premium base resin and high-performance additives to greatly improve shrinkage and mechanical properties, with balanced rigidity and toughness, excellent aging resistance and good processability. For automotive applications they offer low VOC, high flow, high impact strength and flexural modulus, widely used in bumpers, instrument panels, door panels and other interior/exterior parts.","tags":["High","MFI","low","ash","low"],"specsHead":["Description","Grade","Properties","Applications","Technical notes"],"specs":[["1500聚丙烯熔喷布专用料","P6100A15","稳定的高流动性，低碳、环保无毒， 分子量分布窄、 灰分低， 低VOC、无其他产物残留、手感柔软","口罩专用熔喷布","物性表 FDA测试报告 高熔指测试报告"],["1500聚丙烯熔喷布专用料 含驻极母粒","P6100A150Z","稳定的高流动性、低碳、环保无毒， 分子量分布窄、灰分低， 低VOC、 无其他产物残留、手感柔软","KN90/KN95/KN99 口罩专用熔喷布"],["熔喷布高效静电驻极母粒","P6100ZJ","驻留静电荷，提升滤效； 高效、低阻力、不堵孔","熔喷布专用静电驻极"],["无纺布专用纺粘料","P6100F","出丝均匀，高延伸性，力学性能优","口罩内外层无纺布"]],"apps":[["🔧","Medical masks"],["🔧","melt-blown & spunbond fabrics"]],"img":"images/product-pp.webp"},
  'PC/ABS Alloy Series':{"sub":"PC/ABS Alloy Series · — · PC/ABS alloy","meta":{"desc":"PC/ABS alloy","model":"—","feature":"Rigid & tough · impact resistant","apps":"Automotive interior, appliance housings, electronic enclosures"},"intro":"Qide high-performance alloy series blends the advantages of each resin system to deliver balanced rigidity, impact resistance, heat resistance and processability, suited to precision structural and functional parts across automotive, appliance and electronics applications.","tags":["Rigid","&","tough","impact","resistant"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PC/ABS合金（3:7）","CA6130","表面优异，抗冲性好，易成型","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/ABS合金（5:5）","CA6150","表面优异，抗冲性好，光泽度优","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/ABS合金（6:4）","CA6160","表面优异，抗冲性好，高耐热","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/ABS合金阻燃V0级","CAFB6050","表面优异，抗冲性好，光泽度优","汽车零部件，劳保用品，头盔，智能穿戴配件"]],"apps":[["🔧","Automotive interior"],["🔧","appliance housings"],["🔧","electronic enclosures"]],"img":"images/product-pcabs.webp"},
  'PC/PBT Alloy Series':{"sub":"PC/PBT Alloy Series · — · PC/PBT alloy","meta":{"desc":"PC/PBT alloy","model":"—","feature":"Heat & chemical resistant · stable","apps":"Automotive electronics, connectors, enclosures"},"intro":"Qide high-performance alloy series blends the advantages of each resin system to deliver balanced rigidity, impact resistance, heat resistance and processability, suited to precision structural and functional parts across automotive, appliance and electronics applications.","tags":["Heat","&","chemical","resistant","stable"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PC/PBT合金（3:7）","CB6130","表面性好，耐候性优","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/PBT合金（5:5）","CB6150","表面性好，耐候性优","汽车零部件，劳保用品，头盔，智能穿戴配件"],["PC/PBT合金（6:4）","CB6160","表面性好，耐候性优","汽车零部件，劳保用品，头盔，智能穿戴配件"]],"apps":[["🔧","Automotive electronics"],["🔧","connectors"],["🔧","enclosures"]],"img":"images/product-pcabs.webp"},
  'PA6/PA66 Alloy':{"sub":"PA6/PA66 Alloy · — · PA6/PA66 alloy","meta":{"desc":"PA6/PA66 alloy","model":"—","feature":"All-round performance","apps":"Automotive parts, industrial structural parts"},"intro":"Qide high-performance alloy series blends the advantages of each resin system to deliver balanced rigidity, impact resistance, heat resistance and processability, suited to precision structural and functional parts across automotive, appliance and electronics applications.","tags":["All-round","performance"],"specsHead":["Item","Details"],"specs":[["描述","PA6/PA66合金"],["典型规格","N6600"],["典型特点","综合机械性能好"],["典型应用","汽车零部件，婴儿童车"]],"apps":[["🔧","Automotive parts"],["🔧","industrial structural parts"]],"img":"images/product-pcabs.webp"},
  'PA Long-fiber Reinforced Series':{"sub":"PA Long-fiber Reinforced Series · — · PA long-glass-fiber reinforced","meta":{"desc":"PA long-glass-fiber reinforced","model":"—","feature":"High modulus · plastic-for-steel","apps":"Automotive structural parts, power tools, large structural parts"},"intro":"Qide long-glass-fiber reinforced composites keep longer fiber length in the matrix for outstanding modulus, strength and impact resistance, an ideal metal-replacement choice for large structural parts and demanding dynamic applications.","tags":["High","modulus","plastic-for-steel"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PA6+30%LFT","N6130LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"],["PA6+40%LFT","N6140LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"],["PA6+50%LFT","N6150LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"]],"apps":[["🔧","Automotive structural parts"],["🔧","power tools"],["🔧","large structural parts"]],"img":"images/product-lft.webp"},
  'PP Long-fiber Reinforced Series':{"sub":"PP Long-fiber Reinforced Series · — · PP long-glass-fiber reinforced","meta":{"desc":"PP long-glass-fiber reinforced","model":"—","feature":"Lightweight & rigid · metal alternative","apps":"Instrument panel carriers, front-end modules, tailgates"},"intro":"Qide long-glass-fiber reinforced composites keep longer fiber length in the matrix for outstanding modulus, strength and impact resistance, an ideal metal-replacement choice for large structural parts and demanding dynamic applications.","tags":["Lightweight","&","rigid","metal","alternative"],"specsHead":["Description","Typical grade","Typical features","Typical applications"],"specs":[["PP+30%LFT","P6130LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"],["PP+40%LFT","P6140LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"],["PP+50%LFT","P6150LG","高弯曲模量，高抗冲","汽车零部件，运动器材，户外产品"]],"apps":[["🔧","Instrument panel carriers"],["🔧","front-end modules"],["🔧","tailgates"]],"img":"images/product-lft.webp"},
  'PPS Series':{"sub":"PPS Series · — · PPS engineering plastic","meta":{"desc":"PPS engineering plastic","model":"—","feature":"High-temperature resistance","apps":"High-temp electrical & automotive parts"},"intro":"Qide functional material series covers specialty engineering plastics, elastomers and paint-free grades, providing flexible customized solutions for demanding applications.","tags":["High-temperature","resistance"],"specsHead":["Item","Details"],"specs":[["描述","PPS+40%GF"],["典型规格","PPS6140G"],["典型特点","40%GF增强，高弯曲模量，耐热性优"],["典型应用","汽车零部件，充电枪，电子电器"]],"apps":[["🔧","High-temp electrical & automotive parts"]],"img":"images/product-cf.webp"},
  'PPO Series':{"sub":"PPO Series · — · PPO engineering plastic","meta":{"desc":"PPO engineering plastic","model":"—","feature":"Hydrolysis resistant · stable","apps":"Pump housings, electrical parts"},"intro":"Qide functional material series covers specialty engineering plastics, elastomers and paint-free grades, providing flexible customized solutions for demanding applications.","tags":["Hydrolysis","resistant","stable"],"specsHead":["Item","Details"],"specs":[["描述","PPO+20%GF"],["典型规格","PPO6120G"],["典型特点","20%GF增强，尺寸安定性优"],["典型应用","水浴配件，水泵配件，家用电器"]],"apps":[["🔧","Pump housings"],["🔧","electrical parts"]],"img":"images/product-cf.webp"},
  'TPR Series':{"sub":"TPR Series · — · TPR elastomer","meta":{"desc":"TPR elastomer","model":"—","feature":"Soft & elastic","apps":"Grips, seals, consumer goods"},"intro":"Qide functional material series covers specialty engineering plastics, elastomers and paint-free grades, providing flexible customized solutions for demanding applications.","tags":["Soft","&","elastic"],"specsHead":["Item","Details"],"specs":[["描述","抗黄变级"],["典型规格","R6060A-UV"],["典型特点","抗黄变，耐候性优"],["典型应用","手把包胶，工业脚轮，缓冲脚垫"]],"apps":[["🔧","Grips"],["🔧","seals"],["🔧","consumer goods"]],"img":"images/product-cf.webp"},
  'TPU Series':{"sub":"TPU Series · — · TPU elastomer","meta":{"desc":"TPU elastomer","model":"—","feature":"Abrasion resistant · high rebound","apps":"Footwear, films, sports goods"},"intro":"Qide functional material series covers specialty engineering plastics, elastomers and paint-free grades, providing flexible customized solutions for demanding applications.","tags":["Abrasion","resistant","high","rebound"],"specsHead":["Item","Details"],"specs":[["描述","耐磨级"],["典型规格","R6060U"],["典型特点","回弹性优，耐磨性好"],["典型应用","鞋材，电动工具，工业脚轮"]],"apps":[["🔧","Footwear"],["🔧","films"],["🔧","sports goods"]],"img":"images/product-cf.webp"},
  'Paint-free Series':{"sub":"Paint-free Series · — · Paint-free high-appearance grade","meta":{"desc":"Paint-free high-appearance grade","model":"—","feature":"High gloss · eco & cost saving","apps":"Automotive trims, appliance exteriors, consumer electronics"},"intro":"Qide functional material series covers specialty engineering plastics, elastomers and paint-free grades, providing flexible customized solutions for demanding applications.","tags":["High","gloss","eco","&","cost"],"specsHead":["Item","Details"],"specs":[["描述","Custom per requirements"],["典型规格","Custom per requirements"],["典型特点","Custom per requirements"],["典型应用","汽车零部件，家用电器外壳，各类装饰件"]],"apps":[["🔧","Automotive trims"],["🔧","appliance exteriors"],["🔧","consumer electronics"]],"img":"images/product-cf.webp"},
  _default:{sub:'主营产品 · 高强度 · 耐高温 · 尺寸稳定',meta:{desc:'改性工程塑料',model:'多牌号可选',feature:'高强度 · 耐高温 · 尺寸稳定',apps:'新能源汽车、运动器材、高端家电、婴童用品、电子电气等'},intro:'以尼龙（PA）为基体的改性工程塑料，具备高强度、耐热性与尺寸稳定性，广泛应用于新能源汽车、运动器材、高端家电等领域的结构件与功能件。',tags:['耐高温','高强度','尺寸稳定','可定制'],specsHead:['项目','单位','典型值'],specs:[['按需定制','—','按牌号']],apps:[['🚗','新能源汽车'],['🏋','运动器材'],['📺','高端家电'],['👶','婴童用品'],['⚙','电子电气']],img:'images/product-pa.jpg'}
};

if(location.pathname.indexOf('product-detail')>=0){
  const isEn=location.pathname.indexOf('/en/')>=0;
  const name=decodeURIComponent((location.hash||'').replace('#',''))||(isEn?'Modified Nylon (PA)':'改性尼龙复合材料');
  const p=PRODUCTS[name]||PRODUCTS._default;
  document.querySelectorAll('[data-pname]').forEach(el=>el.textContent=name);
  document.title=name+(isEn?' · Qide':' · 奇德新材');
  const sub=document.querySelector('[data-sub]');
  if(sub)sub.textContent=p.sub;
  const intro=document.querySelector('[data-intro]');
  if(intro)intro.textContent=p.intro;
  document.querySelectorAll('[data-meta]').forEach(el=>{const k=el.dataset.meta;if(p.meta[k])el.textContent=p.meta[k];});
  const tags=document.querySelector('[data-tags]');
  if(tags)tags.innerHTML=p.tags.map(t=>'<span>'+t+'</span>').join('');
  const head=document.querySelector('[data-spechead]');
  if(head)head.innerHTML='<tr>'+p.specsHead.map(h=>'<th>'+h+'</th>').join('')+'</tr>';
  const specs=document.querySelector('[data-specs]');
  if(specs)specs.innerHTML=p.specs.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('');
  const apps=document.querySelector('[data-apps]');
  if(apps)apps.innerHTML=p.apps.map(a=>'<div class=app><div class=ico>'+a[0]+'</div><b>'+a[1]+'</b></div>').join('');
  const img=document.querySelector('[data-img]');
  if(img&&p.img){img.src=(isEn?'../':'')+p.img;}
}
